GEMINI_API_KEY = "AIzaSyDYrlyyxB90MoYwV7CGGsQ0Y1ZBHc2ufnE"

FIREBASE_API_KEY = "AIzaSyBPCmpqVsdwD98g4T9_SucRPDe1lo_Th6U"
FIREBASE_AUTH_DOMAIN = "classroomai-ed428.firebaseapp.com"
FIREBASE_PROJECT_ID = "classroomai-ed428"
FIREBASE_STORAGE_BUCKET = "classroomai-ed428.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "478901054017"
FIREBASE_APP_ID = "1:478901054017:web:677a05263a54639ab234c0"
FIREBASE_DATABASE_URL = "https://classroomai-ed428-default-rtdb.firebaseio.com/"